<?xml version="1.0"?>
<package format="3">
  <name>agv_gazebo</name>
  <version>0.0.1</version>
  <description>Gazebo Sim world and AGV model with four corner lidars.</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend condition="$ROS_DISTRO == 'galactic'">ignition-msgs7</depend>
  <depend condition="$ROS_DISTRO == 'galactic'">ignition-transport10</depend>
  <depend condition="$ROS_DISTRO == 'humble'">ros_gz_interfaces</depend>
  <depend condition="$ROS_DISTRO == 'galactic'">ros_ign_interfaces</depend>
  <depend>sensor_msgs</depend>

  <exec_depend>agv_mpc_controller</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
